import BreadCrumbs from "@/components/BreadCrumbs/BreadCrumbs"
import "@gov-design-system-ce/styles/lib/styles.css"
import type { Metadata } from "next"
import NavItem from "./_components/Navbar/NavItem"
import { GovContainer, GovNav } from "./design-system"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const NavItems = [
  { name: "Úvod", href: "/" },
  { name: "Novinky", href: "/novinky" },
  { name: "Legislativa", href: "/legislativa" },
  { name: "Normy", href: "/normy" },
  { name: "Organizace", href: "/organizace" },
  { name: "Záměry", href: "/zamery" },
  { name: "Úřední desky", href: "/uredni-desky" },
  { name: "Akce", href: "/akce" },
  { name: "Kontakty", href: "/kontakt" },
]

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="cs">
      <body>
        {/* Needed to correctly load icons from design system components */}
        {/* TODO: Find out if there is a better place to configure it */}
        <script
          dangerouslySetInnerHTML={{
            __html: `window.GOV_DS_CONFIG = { iconsPath: "/icons" }`,
          }}
        />
        <GovContainer className="bg-red-500">
          <GovNav>
            {NavItems.map(item => (
              <NavItem key={item.name} name={item.name} href={item.href} />
            ))}
          </GovNav>
        </GovContainer>
        <main>
          <GovContainer>
            <BreadCrumbs />
          </GovContainer>
          {children}
        </main>
      </body>
    </html>
  )
}
